### ISSUE TITLE
0.81 compatibility

### ISSUE THREAD

**Issue by krossenheim** [hristoast/tes3mp-mmar#1]
Change line 304 (main.lua) from:

    player:SaveStatsDynamic()
to:
    player:SaveStatsDynamic(player.data)

**Comment by backlabs1** [comment]
The player stats will not update correctly with `player:SaveStatsDynamic(player.data)`. This will result in "not enough magicka" messages if the player depletes their magicka, recharges it with a potion, and then immediately tries to use MMAR again.

We need to read the stats from the client instead and update the stats on the server. The correct line, as far as I can tell, is:

```lua
player:SaveStatsDynamic(packetReader.GetPlayerPacketTables(pid, "PlayerStatsDynamic"))
```

This changes is included in pull request #2.

**Comment by backlabs1** [comment]
Hi @hristoast, perhaps you can merge pull request #2, which fixes this issue? Thanks!

**Comment by hristoast** [comment]
Hey @backlabs1 @krossenheim -- so sorry about the delay and thanks for keeping this script alive. I've merged your fix.

**Comment by backlabs1** [comment]
Hi @hristoast, thanks!
